### ISSUE TITLE
tf_sampling_so.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumE

### ISSUE THREAD

**Issue by jialancong** [yulequan/PU-Net#13]
Hi, thanks for openning your code !

I am using tensorflow 1.7.0 and python 2.7. And I have successfully compiled the operators: emd、grouping、interpolation and sampling using tf_xxx_compile.sh. And in CD subfolder I use tf_cd_compile.sh instead of run "make" because I got `make: Circular tf_nndistance_g.cu <- tf_nndistance_g.cu.o dependency dropped`. when I run "make".

But I still can't run main.py, I got the following error:
```
(py27_1) yjm@gst175060:~/Project/PU-Net/PU-Net-master11_24/PU-Net-master/code$ python main.py --phase train --gpu 2
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import model_generator2_2new6 as MODEL_GEN
  File "/home/yjm/Project/PU-Net/PU-Net-master11_24/PU-Net-master/code/model_generator2_2new6.py", line 3, in <module>
    from utils.pointnet_util import pointnet_sa_module,pointnet_fp_module
  File "/home/yjm/Project/PU-Net/PU-Net-master11_24/PU-Net-master/code/utils/pointnet_util.py", line 9, in <module>
    from tf_ops.sampling.tf_sampling import farthest_point_sample, gather_point
  File "/home/yjm/Project/PU-Net/PU-Net-master11_24/PU-Net-master/code/tf_ops/sampling/tf_sampling.py", line 12, in <module>
    sampling_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_sampling_so.so'))
  File "/home/yjm/anaconda3/envs/py27_1/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/yjm/anaconda3/envs/py27_1/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/yjm/Project/PU-Net/PU-Net-master11_24/PU-Net-master/code/tf_ops/sampling/tf_sampling_so.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumE
```

I would be very grateful if you give me some suggestions ! Thanks!

**Comment by jialancong** [comment]
What I want to know is: How to modify the makefile under CD folder if I use TF version >=1.4 ?

**Comment by yulequan** [comment]
Hi, could you try to add or remove D_GLIBCXX_USE_CXX11_ABI=0 in the .sh file to recompile the files?

**Comment by yulequan** [comment]
I have updated the tf_xx_compile.sh file. You can try it or try
tf_xx_compile_abi.sh file.

**Comment by jialancong** [comment]
@yulequan  Thank you! After removing D_GLIBCXX_USE_CXX11_ABI=0 in the .sh file, I didn't meet NotFoundError, but I got the following error:
```
(py27_1) yjm@gst175060:~/Project/PU-Net/PU-Net-master11_24/PU-Net-master/code$ python main.py --phase train --gpu 2
gst175060
Namespace(batch_size=28, gpu='2', learning_rate=0.001, log_dir='../model/generator2_new6', max_epoch=120, num_point=1024, phase='train', up_ratio=4)
WARNING:tensorflow:From /home/yjm/anaconda3/envs/py27_1/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From /home/yjm/Project/PU-Net/PU-Net-master11_24/PU-Net-master/code/utils/pointnet_util.py:137: calling reduce_max (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/yjm/Project/PU-Net/PU-Net-master11_24/PU-Net-master/code/utils/pointnet_util.py:207: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/yjm/Project/PU-Net/PU-Net-master11_24/PU-Net-master/code/model_utils.py:45: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2018-11-24 13:26:07.363488: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2018-11-24 13:26:07.562743: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:83:00.0
totalMemory: 11.93GiB freeMemory: 11.81GiB
2018-11-24 13:26:07.562810: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-11-24 13:26:08.437796: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-24 13:26:08.437862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-11-24 13:26:08.437878: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-11-24 13:26:08.438350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11438 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:83:00.0, compute capability: 5.2)
use randominput, input h5 file is: ../h5_data/Patches_noHole_and_collected.h5
Traceback (most recent call last):
  File "main.py", line 258, in <module>
    train(assign_model_path=ASSIGN_MODEL_PATH)
  File "main.py", line 143, in train
    use_randominput = USE_RANDOM_INPUT)
  File "/home/yjm/Project/PU-Net/PU-Net-master11_24/PU-Net-master/code/data_provider.py", line 25, in load_patch_data
    input = f['poisson_4096'][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/yjm/anaconda3/envs/py27_1/lib/python2.7/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'poisson_4096' doesn't exist)"
```
Does it mean I hadn't download the dataset?

**Comment by yulequan** [comment]
Maybe the position of h5 file is wrong? Do you download the .h5 file first?

**Comment by jialancong** [comment]
My fualts...Now I can run main.py successfully. Thank you very much @yulequan ! You are helpful !
