### ISSUE TITLE
How to evaluate for test data with variable number of points?

### ISSUE THREAD

**Issue by Lotayou** [yulequan/PU-Net#18]
I have some models and I first downsample them using voxel filter, it turns out that not all the downsampled point cloud has the same number of points (but not too far away either, like 3500+-50). And I got such error at testing stage:

```
2019-01-19 14:46:56.949793: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
../data/test_data/our_collected_data/Dyna_downsampled_voxel_size_0.02/chicken_wings_00124.xyz (1, 3511, 3)
Traceback (most recent call last):
  File "main.py", line 262, in <module>
    prediction_whole_model('../data/test_data/our_collected_data/Dyna_downsampled_voxel_size_0.02')
  File "main.py", line 233, in prediction_whole_model
    pred_pl = sess.run(pred, feed_dict={pointclouds_ipt: input})
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1104, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 3511, 3) for Tensor 'Placeholder:0', which has shape '(1, 3467, 3)'
```
It seems that the number of input points are fixed when creating a model. But I'm wondering if it's possible to support input with variable number of points during test stage? If so, can you tell me how to change the code to achieve this? Thanks!

**Comment by yulequan** [comment]
You can try to change the size of the placeholder as (1, None, 6) in https://github.com/yulequan/PU-Net/blob/master/code/main.py#L201

**Comment by Lotayou** [comment]
I have tried this but turn out it didn't work, with the following error message:
```
Namespace(batch_size=28, gpu='0', learning_rate=0.001, log_dir='../model/generator2_new6', max_epoch=120, num_point=1024, phase='test', test_dir='../data/test_data/Dyna_varied_num_of_points/Dyna_downsampled_voxel_size_0.03', up_ratio=4)
Traceback (most recent call last):
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 152, in _MakeInt
    return int(v)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 266, in <module>
    prediction_whole_model(data_folder=TEST_INPUT_DIR)
  File "main.py", line 211, in prediction_whole_model
    reuse=None, use_normal=use_normal, use_bn=False, use_ibn=False, bn_decay=0.95, up_ratio=UP_RATIO)
  File "/backup/home/ylb/projects/3D_mesh_SR/PU-Net/code/model_generator2_2new6.py", line 27, in get_gen_model
    is_training=is_training, bn_decay=bn_decay, scope='layer1')
  File "/backup/home/ylb/projects/3D_mesh_SR/PU-Net/code/utils/pointnet_util.py", line 120, in pointnet_sa_module
    new_xyz, new_points, idx, grouped_xyz = sample_and_group(npoint, radius, nsample, xyz, points, tnet_spec, knn, use_xyz)
  File "/backup/home/ylb/projects/3D_mesh_SR/PU-Net/code/utils/pointnet_util.py", line 35, in sample_and_group
    new_xyz = gather_point(xyz, farthest_point_sample(npoint, xyz)) # (batch_size, npoint, 3)
  File "/backup/home/ylb/projects/3D_mesh_SR/PU-Net/code/tf_ops/sampling/tf_sampling.py", line 56, in farthest_point_sample
    return sampling_module.farthest_point_sample(inp, npoint)
  File "<string>", line 49, in farthest_point_sample
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in _apply_op_helper
    attr_value.i = _MakeInt(value, key)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 155, in _MakeInt
    (arg_name, repr(v)))
TypeError: Expected int for argument 'npoint' not None.
vcl-dl-3
Namespace(batch_size=28, gpu='0', learning_rate=0.001, log_dir='../model/generator2_new6', max_epoch=120, num_point=1024, phase='test', test_dir='../data/test_data/Dyna_varied_num_of_points/Dyna_downsampled_voxel_size_0.05', up_ratio=4)
Traceback (most recent call last):
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 152, in _MakeInt
    return int(v)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 266, in <module>
    prediction_whole_model(data_folder=TEST_INPUT_DIR)
  File "main.py", line 211, in prediction_whole_model
    reuse=None, use_normal=use_normal, use_bn=False, use_ibn=False, bn_decay=0.95, up_ratio=UP_RATIO)
  File "/backup/home/ylb/projects/3D_mesh_SR/PU-Net/code/model_generator2_2new6.py", line 27, in get_gen_model
    is_training=is_training, bn_decay=bn_decay, scope='layer1')
  File "/backup/home/ylb/projects/3D_mesh_SR/PU-Net/code/utils/pointnet_util.py", line 120, in pointnet_sa_module
    new_xyz, new_points, idx, grouped_xyz = sample_and_group(npoint, radius, nsample, xyz, points, tnet_spec, knn, use_xyz)
  File "/backup/home/ylb/projects/3D_mesh_SR/PU-Net/code/utils/pointnet_util.py", line 35, in sample_and_group
    new_xyz = gather_point(xyz, farthest_point_sample(npoint, xyz)) # (batch_size, npoint, 3)
  File "/backup/home/ylb/projects/3D_mesh_SR/PU-Net/code/tf_ops/sampling/tf_sampling.py", line 56, in farthest_point_sample
    return sampling_module.farthest_point_sample(inp, npoint)
  File "<string>", line 49, in farthest_point_sample
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in _apply_op_helper
    attr_value.i = _MakeInt(value, key)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 155, in _MakeInt
    (arg_name, repr(v)))
TypeError: Expected int for argument 'npoint' not None.

```

However I found a nasty workaround: I can assign the input of maximum number of points in my testing dataset, and for each file, I randomly replicate some point to enforce the total number of points to reach this maximum. But I'm not sure if it's safe to do so, do you think this operation would make a huge difference? Thanks!

**Comment by yulequan** [comment]
I think your solution is reasonable. In another way, you can try to put the code of building the graph into the for loop, which means building a new graph for each test case.
