### ISSUE TITLE
How to prepare dataset

### ISSUE THREAD

**Issue by Lotayou** [yulequan/PU-Net#19]
Hi, I have a human 3D mesh dataset and I want to train your model on this dataset. Can you tell me how to prepare training data? What's the required format of the training .h5 file?

Also, human mesh is a closed surface, do I need to separate different body parts or can I just throw the whole human as input? Thanks!

**Comment by yulequan** [comment]
1. The training is based on patches. So you first need to divide the training meshes into patches and use 
Poisson disk sampling to sample uniform point set from each patch. 
2. I think separating into different body parts would have a better performance.

**Comment by Lotayou** [comment]
Thanks for your prompt reply! BTW, what package do you use for Poisson disk sampling? Most implementations I found online are voxel downsampling, which tend to remove facial landmarks and result in bad reconstruction results.

**Comment by yulequan** [comment]
You can find the related code in https://github.com/yulequan/PU-Net/tree/master/prepare_data

**Comment by Lotayou** [comment]
Hey I prepared my dataset as instructed and pre-processing is fine. However I encountered the following error during training, which is pretty weird:
```
**** EPOCH 000 ****
Traceback (most recent call last):
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: AuctionMatch handles at most 4096 dataset points
         [[Node: AuctionMatch = AuctionMatch[_device="/job:localhost/replica:0/task:0/device:GPU:0"](generator/Squeeze, _arg_Placeholder_1_0_1/_187)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 281, in <module>
    train(assign_model_path=ASSIGN_MODEL_PATH)
  File "main.py", line 168, in train
    train_one_epoch(sess, ops, fetchworker, train_writer)
  File "main.py", line 186, in train_one_epoch
    ops['pred'], ops['gen_loss_emd']], feed_dict=feed_dict)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: AuctionMatch handles at most 4096 dataset points
         [[Node: AuctionMatch = AuctionMatch[_device="/job:localhost/replica:0/task:0/device:GPU:0"](generator/Squeeze, _arg_Placeholder_1_0_1/_187)]]

Caused by op 'AuctionMatch', defined at:
  File "main.py", line 281, in <module>
    train(assign_model_path=ASSIGN_MODEL_PATH)
  File "main.py", line 84, in train
    gen_loss_emd,matchl_out = model_utils.get_emd_loss(pred, pointclouds_gt, pointclouds_radius)
  File "/backup/home/ylb/projects/3D_mesh_SR/PU-Net/code/model_utils.py", line 42, in get_emd_loss
    matchl_out, matchr_out = tf_auctionmatch.auction_match(pred, gt)
  File "/backup/home/ylb/projects/3D_mesh_SR/PU-Net/code/tf_ops/emd/tf_auctionmatch.py", line 19, in auction_match
    return auctionmatch_module.auction_match(xyz1,xyz2)
  File "<string>", line 39, in auction_match
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/backup/home/ylb/.conda/envs/yanglingbo/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): AuctionMatch handles at most 4096 dataset points
         [[Node: AuctionMatch = AuctionMatch[_device="/job:localhost/replica:0/task:0/device:GPU:0"](generator/Squeeze, _arg_Placeholder_1_0_1/_187)]]
```

It seems to me that some Tensorflow build-in layers can not handle point cloud with more than 4096 points. Do you know any quick workaround for this issue so I don't need to perform further sampling? Just wondering ... thanks

**Comment by yulequan** [comment]
Yes, the EMD distance function can only handle less than 4096 points.
