### ISSUE TITLE
Error in training ( tf_sampling_so.so ) 

### ISSUE THREAD

**Issue by ahmedwael19** [yulequan/PU-Net#25]
Hello, 
I am trying to run the code but no luck so far.
I am using Python 3 , CUDA 10, and Tensorflow 1.13.1

I compiled all the files with warnings but no errors.
However, when I try to run the code (training) , I get the following error.

`Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import model_generator2_2new6 as MODEL_GEN
  File "/home/ahmed/PU-Net/code/model_generator2_2new6.py", line 3, in <module>
    from utils.pointnet_util import pointnet_sa_module,pointnet_fp_module
  File "/home/ahmed/PU-Net/code/utils/pointnet_util.py", line 9, in <module>
    from tf_ops.sampling.tf_sampling import farthest_point_sample, gather_point
  File "/home/ahmed/PU-Net/code/tf_ops/sampling/tf_sampling.py", line 12, in <module>
    sampling_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_sampling_so.so'))
  File "/home/ahmed/.local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/ahmed/PU-Net/code/tf_ops/sampling/tf_sampling_so.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
`

I am sure that the files are all there and everything.
I have also tried compling _abi instead of the original sh files, but no luck also.

Would really appreciate your response.

**Comment by yulequan** [comment]
Hi, after some simple search, this problem may be related to the version of Cmake and ABI. See this link [https://github.com/lmb-freiburg/demon/issues/26]. Maybe the simple way is downgrading the TF version.

**Comment by ahmedwael19** [comment]
Thank you so much for your reply.
Is there is a way to downgrade the TF version without breaking the whole environment ( CUDA, GPU drivers, etc) ?

**Comment by yulequan** [comment]
I think you can use virtual environments, such as Anaconda.

**Comment by xuehuang-web** [comment]
hello，How did you solve the problem？
