### ISSUE TITLE
ValueError during training

### ISSUE THREAD

**Issue by Taeuk-Jang** [yulequan/PU-Net#30]
Thank you for the excellent code in advance.
I followed the instructions but I encountered an error while training.
I think the training data has been successfully loaded, but it says 'ValueError' when training.
Also I tried:

`try:
xc = int(np.round(xc))
except:
continue
`
and 
`if not np.isnan(xc)
...`

but I think it doesn't train well according to evaluation.
The output while training is as below:

> use randominput, input h5 file is: ../h5_data/Patches_noHole_and_collected.h5
Normalization the data
load object names ['Pyramid', 'armadillo', 'big', 'block', 'boy01', 'boy02', 'bumpy', 'bunny', 'cad', 'ccylinder', 'child', 'chinese', 'cone', 'cup', 'david', 'dino', 'egea', 'ellipsoid', 'eros', 'fish', 'focal-octa', 'gargoyle', 'girl', 'hand', 'joint', 'julius', 'nicolo', 'octa-flower', 'pierrot', 'pulley', 'pyramid', 'retinal', 'rolling', 'screwdriver', 'sharp', 'special', 'star', 'turbine', 'twirl', 'vaselion']
total 4000 samples
NUM_BATCH is 142
True True
  0%|                          | 0/121 [00:00<?, ?it/s]2019-08-20 14:35:17.966225: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
Traceback (most recent call last):
  File "main.py", line 258, in <module>
    train(assign_model_path=ASSIGN_MODEL_PATH)
  File "main.py", line 149, in train
    train_one_epoch(sess, ops, fetchworker, train_writer)
  File "main.py", line 174, in train_one_epoch
    pointclouds_image_pred = pc_util.point_cloud_three_views(pred_val[0, :, :])
  File "/home/taeuk/network/PU-Net/code/utils/pc_util.py", line 186, in point_cloud_three_views
    img1 = draw_point_cloud(points, zrot=110 / 180.0 * np.pi, xrot=135 / 180.0 * np.pi, yrot=0 / 180.0 * np.pi,diameter=diameter)
  File "/home/taeuk/network/PU-Net/code/utils/pc_util.py", line 151, in draw_point_cloud
    xc = int(np.round(xc))
ValueError: cannot convert float NaN to integer

**Comment by jianing-li** [comment]
I have same problem!

**Comment by WonderWuss** [comment]
Hi, Do you fix this? I face the same problem and have no clue.
